version: "3.1"

# services
services:
 projeto1:
  image: registry.churrops.com/projeto1:{{ version }}
  command: ./start.sh
  networks:
   - churrops
  deploy:
   replicas: 3
   placement:
    constraints: [node.role == worker]
   labels:
    #- "traefik.backend=http"
    - "traefik.port=80"
    - "traefik.frontend.rule=Host:prod.churrops.com"

networks:
 churrops:
  driver: overlay
  ipam:
   config:
    - subnet: 192.168.0.0/24
