kind: Service
apiVersion: v1
metadata:
  name: projeto1
spec:
  selector:
    app: projeto1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: projeto1
  labels:
    app: projeto1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: projeto1
  template:
    metadata:
      labels:
        app: projeto1
    spec:
      containers:
      - name: projeto1
        image: registry.churrops.com/projeto1:latest
        command: ["./start.sh"]
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regsecret
