#
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
 name: projeto1-st
spec:
 replicas: 3
 selector:
  matchLabels:
   app: projeto1-st
 template:
  metadata:
   labels:
    app: projeto1-st
  spec:
   containers:
   - name: projeto1-st
     image: registry.churrops.com/projeto1:{{ version }}
     command: ["./start.sh"]
     ports:
     - containerPort: 80
   imagePullSecrets:
   - name: regsecret
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: projeto1-st
  name: projeto1-st
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: projeto1-st
  sessionAffinity: None
  type: LoadBalancer
